### ISSUE TITLE
Создай файл main.py

### ISSUE THREAD

**Issue by ShvonderSiN** [ShvonderSiN/git_homework#1]
Создай файл main.py (в отдельной ветке, разумеется)
в блоке if main выведи принт хеллоу ворлд

**Comment by ShaoYoung** [comment]
Принял

**Comment by ShaoYoung** [comment]
Задание сделал. Только, похоже, после create pull request зря нажал merge pull request (запамятовал).

**Comment by ShaoYoung** [comment]
Да, надо сразу доступ к main ограничивать.
